CREATE TABLE IF NOT EXISTS "types" (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"date_created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"date_modified" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"notes" TEXT
);

CREATE TABLE CATEGORIES (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"type_id_default" BIGINT,
	"color" TEXT,
	"icon_path" TEXT,
	"icon_char" TEXT,
	"description" TEXT,
	"notes" TEXT,
	"date_created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"date_modified" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (TYPE_ID_DEFAULT) REFERENCES TYPES (ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "trips" (
	"id" SERIAL PRIMARY KEY,
	"name" TEXT NOT NULL UNIQUE,
	"date_start" DATE,
	"date_end" DATE,
	"description" TEXT,
	"color" TEXT,
	"date_created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"date_modified" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "transactions" (
	"id" SERIAL PRIMARY KEY,
	"date" DATE NOT NULL,
	"description" TEXT NOT NULL,
	"type_id" BIGINT,
	"amount" NUMERIC(12, 2) NOT NULL,
	"category_id" BIGINT,
	"trip_id" BIGINT,
	"notes" TEXT,
	"date_created" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"date_modified" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY ("trip_id") REFERENCES "trips" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
	FOREIGN KEY ("type_id") REFERENCES "types" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE OR REPLACE FUNCTION UPDATE_DATE_MODIFIED () RETURNS TRIGGER AS $$
BEGIN
    NEW.date_modified = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE TRIGGER TRG_UPDATE_TYPES BEFORE
UPDATE ON TYPES FOR EACH ROW
EXECUTE FUNCTION UPDATE_DATE_MODIFIED ();

CREATE TRIGGER TRG_UPDATE_CATEGORIES BEFORE
UPDATE ON CATEGORIES FOR EACH ROW
EXECUTE FUNCTION UPDATE_DATE_MODIFIED ();

CREATE TRIGGER TRG_UPDATE_TRIPS BEFORE
UPDATE ON TRIPS FOR EACH ROW
EXECUTE FUNCTION UPDATE_DATE_MODIFIED ();

CREATE TRIGGER TRG_UPDATE_TRANSACTIONS BEFORE
UPDATE ON TRANSACTIONS FOR EACH ROW
EXECUTE FUNCTION UPDATE_DATE_MODIFIED ();
